export var people = [
  { id: 1, name: 'John', age: 25, city: 'New York' },
  { id: 2, name: 'Alice', age: 30, city: 'Los Angeles' },
  { id: 3, name: 'Bob', age: 22, city: 'Chicago' },
  { id: 4, name: 'Emily', age: 28, city: 'San Francisco' },
  { id: 5, name: 'David', age: 40, city: 'Miami' },
  { id: 6, name: 'Sophia', age: 32, city: 'Seattle' },
  { id: 7, name: 'Michael', age: 27, city: 'Boston' },
  { id: 8, name: 'Olivia', age: 29, city: 'Austin' },
  { id: 9, name: 'William', age: 35, city: 'Denver' },
  { id: 10, name: 'Ava', age: 31, city: 'Atlanta' },
  { id: 11, name: 'James', age: 26, city: 'Philadelphia' },
  { id: 12, name: 'Emma', age: 24, city: 'Dallas' },
  { id: 13, name: 'Liam', age: 33, city: 'Houston' },
  { id: 14, name: 'Mia', age: 23, city: 'Phoenix' },
  { id: 15, name: 'Benjamin', age: 37, city: 'San Diego' },
  { id: 16, name: 'Isabella', age: 38, city: 'Portland' },
  { id: 17, name: 'Ethan', age: 39, city: 'Nashville' },
  { id: 18, name: 'Charlotte', age: 34, city: 'Detroit' },
  { id: 19, name: 'Alexander', age: 29, city: 'Minneapolis' },
  { id: 20, name: 'Amelia', age: 30, city: 'Orlando' },
  { id: 21, name: 'Daniel', age: 28, city: 'Raleigh' },
  { id: 22, name: 'Abigail', age: 26, city: 'Salt Lake City' },
  { id: 23, name: 'Matthew', age: 27, city: 'Las Vegas' },
  { id: 24, name: 'Harper', age: 25, city: 'Kansas City' },
  { id: 25, name: 'Andrew', age: 36, city: 'San Antonio' },
  { id: 26, name: 'Elizabeth', age: 31, city: 'Tampa' },
  { id: 27, name: 'Joseph', age: 33, city: 'Columbus' },
  { id: 28, name: 'Sofia', age: 24, city: 'Charlotte' },
  { id: 29, name: 'William', age: 32, city: 'St. Louis' },
  { id: 30, name: 'Ella', age: 30, city: 'Indianapolis' },
  { id: 31, name: 'James', age: 28, city: 'New Orleans' },
  { id: 32, name: 'Grace', age: 27, city: 'Seattle' },
  { id: 33, name: 'David', age: 29, city: 'Denver' },
  { id: 34, name: 'Avery', age: 25, city: 'Phoenix' },
  { id: 35, name: 'Daniel', age: 26, city: 'Atlanta' },
  { id: 36, name: 'Victoria', age: 31, city: 'Miami' },
];
